### ISSUE TITLE
Searching with Contains() with a part of a word doesn't work

### ISSUE THREAD

**Issue by mahgo** [base33/umbraco.examine.linq#11]
If using Where(x => x.Name.Contains("Fo")), "Foo" is not matched. Is there a way to make this work?

**Comment by base33** [comment]
Hi Mahgo

You can do "fo*". Lucene does word based searched based on your searcher settings. Adding the * can do a wildcard

Thanks 
Craig

**Comment by mahgo** [comment]
Thanks for that.
