### ISSUE TITLE
A few errors in the Expression logic documentation for != operator

### ISSUE THREAD

**Issue by joshua-stewart** [base33/umbraco.examine.linq#3]
There are a few errors in the Expression logic documentation for != operator

In string logic: the != example should be r => r.Name != "foo"

In bool logic: the != example should be r => r.UmbracoNaviHide != false

Thank you for this fantastic package.

**Comment by base33** [comment]
Thank you very much for letting me know :-)

**Comment by joshua-stewart** [comment]
You're welcome.
