### ISSUE TITLE
Add ability to use custom mapper to produce results.

### ISSUE THREAD

**Issue by JimBobSquarePants** [base33/umbraco.examine.linq#5]
At present it looks like mapping is hard coded. 

https://github.com/base33/umbraco.examine.linq/blob/1efd61fb429108ee0015e9e59dc6fae0d9623897/Umbraco.Examine.Linq/Mapper/SearchResultMapper.cs

It would be nice if I could plug something like Ditto into the pipeline to conduct the mapping.

**Comment by base33** [comment]
Hey James,

Absolutely agree.  Finished parts of the Linq functionality for version 1.1 now.  So this will be my next visit.

My initial thought is to inject the mapping class into the Index constructor.  Do you use the Field attributes on your Ditto-based classes?

So would something like the below be how you would want to specify your own mapping?

```C#
IEnumerable<DittoBasedClass> results = new Index<DittoBasedClass>(new DittoMapper()).Where(r => r.Name.Contains("something")).ToList();  
```
Then the above could then use the DittoMapper to map to the DittoBasedClass instances.  

Thanks :-)

Craig

**Comment by base33** [comment]
Hey James,

Just to let you know this is now in version 1.2.

You just implement IMapper and inject it in the constructor.  Works well with Ditto, etc.

Hope this helps.

Cheers

Craig
