### ISSUE TITLE
Getting query results count

### ISSUE THREAD

**Issue by mahgo** [base33/umbraco.examine.linq#9]
Is it possible to get the results count after building a query, without using ToList() (which loads it all into memory)? 

`Index<FooResult> index = Index<FooResult>("FooSearcher");
IQueryable<FooResult> query = index.Where(x => x.NodeTypeAlias = "Foo");
int count = query.Count();`

throws an InvalidCastException "Unable to cast object of type 'System.Collections.Generic.List`1[FooProject.Models.FooResult]' to type 'System.Collections.Generic.IEnumerable`1[System.Int32]'."

**Comment by base33** [comment]
Hi @mahgo 

You will need to call .ToList() for it to evaluate the expression and query the index.  That will fix that problem for you :-)

Thanks,

Craig

**Comment by mahgo** [comment]
Hi @base33 

My main concern with doing that is that calling .ToList() will then proceed to load all that data into memory, which is not an efficient way of doing it. Is querying the index just for the results count possible, or is this something that even Examine doesn't support?

**Comment by base33** [comment]
Hi @mahgo 

Examine doesn't support that as far as I am aware.  I am wondering whether this is something I can build in, possibly by bypassing Examine.  

I am considering removing Examine from this completely, as in theory this would work directly with Lucene.  I know Lucene does support this via 'TotalHits'.  I am wondering whether you could write your own Searcher, by passing it in to the Index constructor.  Your searcher would receive the generated Query and you can get the count via that.

Hope that helps!

Thanks,

Craig

**Comment by mahgo** [comment]
Thanks for that Craig
